FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /app
COPY elams-microservices/api-gateway/.mvn/ .mvn
COPY elams-microservices/api-gateway/mvnw elams-microservices/api-gateway/pom.xml ./
RUN chmod +x mvnw && ./mvnw dependency:go-offline
COPY elams-microservices/api-gateway/src ./src
RUN ./mvnw package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 9090
ENTRYPOINT ["java", "-jar", "app.jar"]
