FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /app
COPY elams-microservices/config-server/.mvn/ .mvn
COPY elams-microservices/config-server/mvnw elams-microservices/config-server/pom.xml ./
RUN chmod +x mvnw && ./mvnw dependency:go-offline
COPY elams-microservices/config-server/src ./src
RUN ./mvnw package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8888
ENTRYPOINT ["java", "-jar", "app.jar"]
