FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /app
COPY elams-microservices/employee-management/.mvn/ .mvn
COPY elams-microservices/employee-management/mvnw elams-microservices/employee-management/pom.xml ./
RUN chmod +x mvnw && ./mvnw dependency:go-offline
COPY elams-microservices/employee-management/src ./src
RUN ./mvnw package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 9191
ENTRYPOINT ["java", "-jar", "app.jar"]
